version: '3.9'
# compose name
name: project-my-compose

services:
  app:
    container_name: gosvc_container
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    build:
      context: ./project-my-compose/
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - 4331:77
    networks:
      - net_mycompose_dzakwandaffar

  postgresdb:
    image: postgres:latest
    container_name: dbsvc_container
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_NAME=${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - vol_mycompose_dzakwandaffar:/var/lib/postgresql/data
    networks:
      - net_mycompose_dzakwandaffar

volumes:
  vol_mycompose_dzakwandaffar:

networks:
  net_mycompose_dzakwandaffar:
    driver: bridge